name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  findVersion:
    runs-on: ubuntu-latest
    name: "server ${{ matrix.platform }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "versions"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1